### PR TITLE
feat: add `avif` format support

### PR DESCRIPTION
**Pull request by tasiotas**
added `avif` support.

### 🔗 Linked issue

addresses #2 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

To be honest, I have very little confidence in size calculation. I added few samples to make sure it works and it does.
Couldn't find any documentation where width and height is stored in avif/heic files, I just found it by hand. Perhaps that's how it's done?

Also this is my very first PR ever, hope I didn't forget anything here.
thanks

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tasiotas** [comment]
hi @pi0, any chance to have it merged in?
I am looking forward to `nuxt/image` / `ipx` have `avif` support as source image.

**Comment by Irelynx** [comment]
Hi @tasiotas,

First of all, thanks you for your pull-request. I was able to found it because I have issues with AVIF files as an input for unjs/IPX.

> To be honest, I have very little confidence in size calculation. I added few samples to make sure it works and it does. Couldn't find any documentation where width and height is stored in avif/heic files, I just found it by hand. Perhaps that's how it's done?

Seems like your solution indeed is not correct (I checked manually some of my AVIF files and there are invalid width and height values at offsets 0xc4 (196) and 0xc8 (200))

Here is some information that I found in internet, that seems to be correct:
* [StackOverflow](https://stackoverflow.com/questions/66222773/how-to-get-image-dimensions-from-an-avif-file)
* [libavif source code (github)](https://github.com/AOMediaCodec/libavif/blob/6ec8bfd8c4237a72e5364c23594b337021428381/src/write.c#L2608)
* I also checked ISO/IEC 23008-12 and 14496-12

One can get AVIF dimensions by finding `ispe` (Image spatial extents) section offset:
* width: `ispe offset` + 8
* height: `ispe offset` + 12

Please note that offset of `ispe` section should be after `ftyp` (File Type Box) (`ftypavif` in AVIF case), then after `meta` (Meta Box), then after `iprp` (Item Properties Box), then after `ipco` (Item Property Container Box), but before `mdat` (Media Data Box) and also before `iprp offset` + `iprp length` (can be retrieved by reading uint32BE at `iprp offset` + 4, so it is located right after `iprp`)

Here is an structure example of my test file:
```
FileTypeBox 'ftyp': major-brand='avif', compatible-brands='avif mif1 miaf MA1B'
    MetaBox 'meta': (container)
        HandlerBox 'hdlr': v0, 'pict' ('libavif')
        PrimaryItemBox 'pitm': v0, item_ID=1;
        ItemLocationBox 'iloc': (skipped, not required)
        ItemInfoBox 'iinf': (skipped, not required)
        ItemReferenceBox 'iref': (skipped, not required)
        ItemPropertiesBox 'iprp': (length: 195 bytes)
            ItemPropertyContainerBox 'ipco': (length: 157 bytes)
                ImageSpatialExtentsProperty 'ispe': v0, f0, w=1100, h=1100

                PixelInformationProperty 'pixi': (skipped, not required)
                ??? 'av1C': (unknown, seems like related to AVIF somehow, contain 4 bytes)
                ColourInformationBox 'colr': (skipped, not required)
                PixelInformationProperty 'pixi': (skipped, not required)
                ??? 'av1C': (again)
                AuxiliaryTypeProperty 'auxC': v0, f0, (contains `urn:mpeg:mpegB:cicp:systems:auxiliary:alpha`, required?)
           ItemPropertyAssociation 'ipma': (skipped, but required by ISO)
    MediaDataBox 'mdat' or 'idat': (image data)
```

First 512 bytes (header + image data start)
```
00000020667479706176696600000000617669666D6966316D6961664D4131420000018D6D657461000000000000002868646C720000000000000000706963740000000000000000000000006C696261766966000000000E7069746D0000000000010000002C696C6F6300000000440000020001000000010000164D00003D02000200000001000001B5000014980000004269696E660000000000020000001A696E6665020000000001000061763031436F6C6F72000000001A696E6665020000000002000061763031416C706861000000001A69726566000000000000000E6175786C000200010001000000C3697072700000009D6970636F0000001469737065000000000000044C0000044C000000107069786900000000030808080000000C6176314381080C0000000013636F6C726E636C78000200020006800000000E706978690000000001080000000C6176314381081C0000000038617578430000000075726E3A6D7065673A6D706567423A636963703A73797374656D733A617578696C696172793A616C706861000000001E69706D6100000000000000020001040102830400020401058607000051A26D64617412000A071A2AA25C4BE150328A29132029A450F4CE11DA346A46B821BAA56E3F6571A3F9C8CCABFB0FBF837E854F4458D535F406A49A26378811B7641D3DD918573F9B6217589351BA9C58
```
image

**Comment by tasiotas** [comment]
hi @Irelynx thank you so much for very detailed explanation.
I added incremental box search functionality to drill down to `ispe` box.

Works on my samples, but it would be good to test it on your images that were failing for you before.

**Review by pi0 — APPROVED** [review]
Thanks ❤️

**Pull request merged**
